NiñasProject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

import usuarios

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("usuarios.urls")),
    path('', include("cursos.urls")),
    path('coordinadora/', include("coordinacion.urls", namespace='coordinacion')),
    path('', include("asistencia.urls")),
    path('',include("problemas.urls")),
    path('',include("clases.urls")),
    path('',include("feedback.urls")),
] +static(settings.MEDIA_URL, document_ROOT=settings.MEDIA_ROOT)

clases/urls.py
from django.urls import path, include

from clases import views

app_name = 'clases'
urlpatterns = [
    path('<int:curso_id>/agregar-clase/', views.CrearClaseView.as_view(), name='agregar_clase'),
]

cursos/urls.py
from django.urls import path, include

from cursos import views

app_name = 'cursos'
urlpatterns = [
    path('<int:curso_id>/curso/', views.CursoView.as_view(), name='curso'),
    path('<int:curso_id>/curso/<str:order>/', views.CursoView.as_view(), name='curso'),
    path('mis_cursos/', views.MisCursosView.as_view(), name='mis_cursos'),
    path('<int:curso_id>/estadisticas/', views.EstadisticasView.as_view(), name='estadisticas'),

]

feedback/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from feedback import views

app_name = 'feedback'
urlpatterns = [
    path('casos-alternativos', views.CasosAlternativos.as_view(),name='casos-alternativos'),
    path('<int:caso_id>/actualizar-outputs-alternativos', views.ActualizarOutputsAlternativos.as_view(),name='actualizar-outputs-alternativos'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

problemas/urls.py
import cursos
from django.urls import path
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static

from problemas import views

app_name = 'problemas'

urlpatterns = [
    path('<int:curso_id>/curso/<int:problema_id>/problema/enunciado/<int:result>', views.ProblemasViews.as_view(tab='enunciado'), name='enunciado-problema'),
    path('<int:curso_id>/curso/<int:problema_id>/problema/casos/<int:result>', views.ProblemasViews.as_view(tab='casos'), name='casos-problema'),
    path('<int:curso_id>/curso/<int:problema_id>/problema/feedback/<int:result>', views.ProblemasViews.as_view(tab='feedback'), name='feedback-problema'),
    path('<int:clase_id>/agregar-problema', views.CrearProblemasViews.as_view(), name='crear-problema'),
    path('<int:curso_id>/curso/<int:problema_id>/problema/edit/', views.EditarProblemasViews.as_view(), name='editar-problema')
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

problemas/models.py
import os
import json
from django.conf import settings
from django.core.validators import FileExtensionValidator
from django.db import models

from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils import timezone
from django.core.files import File

from clases.models import Clase
from my_lib.files_wrapper import file_to_file, change_path_extension, get_file_name, check_if_file_is_valid


class Problema(models.Model):
    titulo = models.CharField(max_length=100)
    fecha_creacion = models.DateTimeField(editable=False, blank=True, null=True)

    statement = models.FileField(upload_to='statements', help_text="Solo se aceptan PDF's",
                                 validators=[FileExtensionValidator(['pdf'])])

    # The source with which the statement file was created (a .zip or another compression format)
    source = models.FileField(upload_to='source', blank=True, null=True)

    tests = models.FileField(upload_to='test_files', help_text="Se aceptan formatos .csv y .json",
                             validators=[FileExtensionValidator(['json', 'csv']), check_if_file_is_valid])
    clase = models.ForeignKey(Clase, blank=True, null=True, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        """
        On save, update timestamps
        """
        if not self.id:
            self.fecha_creacion = timezone.now()
        self.updated_at = timezone.now()

        return models.Model.save(self, *args, **kwargs)

    def __str__(self):
        return self.titulo

    def get_source_name(self):
        return self.source.name.split("/")[-1]

    def get_statement_name(self):
        return self.statement.name.split("/")[-1]

    def get_tests_name(self):
        return self.tests.name.split("/")[-1]


@receiver(post_save, sender=Problema)
def create_assignment(sender, instance, created, **kwargs):
    """
    Changes the file to a json on creation

    :param sender: The model class. (Assignment)
    :param instance: The actual instance being saved.
    :param created: Boolean; True if a new record was created.
    """

    if created and instance.tests:
        # Generates paths for the new json file
        test_url = instance.tests.url[1:]
        json_tests_url = change_path_extension(test_url, 'json')

        # Passes the information from the original file to the json file
        file_to_file(test_url, json_tests_url)

        # Saves the new json file as the tests file in the instance
        f = open(json_tests_url)
        instance.tests.save(get_file_name(json_tests_url), File(f))
        f.close()

        # Deletes the old file
        os.remove(test_url)
        create_test_cases(instance)


def create_test_cases(problema):
    with open(settings.BASE_DIR + problema.tests.url, 'r', encoding='utf-8-sig') as f:
        datastore = json.load(f)

    for test_dict in datastore:  # Aquí es donde se generan los test, tengo que modificar para que reciba mi nueva info.
        caso = Caso(categoría=test_dict["Categoria"], input=test_dict["Input"], output_esperado=test_dict["Output"],
                    problema=problema)
        caso.save()


class Caso(models.Model):
    categoría = models.TextField(help_text="Descripción del caso")
    input = models.CharField(max_length=255, help_text="Input del caso")
    output_esperado = models.CharField(max_length=255, help_text="Output esperado para el input")
    problema = models.ForeignKey(Problema, on_delete=models.CASCADE, help_text="Problema al que pertenece el caso")

    def __str__(self):
        return self.problema.titulo + "-" + str(self.id)

problemas/forms.py
from django.forms import ModelForm

from django.contrib.admin.widgets import AdminFileWidget
from django.forms.widgets import HiddenInput, FileInput

from problemas.models import Problema


class ProblemaForm(ModelForm):
    class Meta:
        model = Problema
        exclude = ['source', 'fecha_creacion', 'clase']

problemas/views.py
import os

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponseForbidden, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import TemplateView

from NiñasProject.decorators import profesora_required
from NiñasProject.utils import get_ordered_test_feedback, get_casos_por_categoria, get_cursos, problema_en_curso
from clases.models import Clase
from cursos.models import Curso
from feedback.models import Feedback, TestFeedback, OutputAlternativo
from problemas.forms import ProblemaForm
from problemas.models import Problema, Caso

from scriptserver.comunication.client import Client

ComunicationClient = Client()


class ProblemasViews(LoginRequiredMixin, TemplateView):
    tab = 'enunciado'
    login_url = 'usuarios:login'
    redirect_field_name = ''
    template_name = "problemas/inicio_problemas.html"
    feedback_template_name = "problemas/inicio_problemas.html"
    feedback_error_template_name = "error.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        problema = get_object_or_404(Problema, id=self.kwargs['problema_id'])
        curso = get_object_or_404(Curso, id=self.kwargs['curso_id'])

        context['curso'] = curso
        context['problema'] = problema
        context['has_tests'] = bool(problema.tests)
        context['casos'] = get_casos_por_categoria(Caso.objects.filter(problema=problema))

        nuevos_outputs = {}
        for caso in Caso.objects.filter(problema=problema):
            nuevos_outputs[caso.id] = OutputAlternativo.objects.filter(caso=caso, agregado=False).count()
        context['nuevos_outputs'] = nuevos_outputs

        if self.tab == 'enunciado':
            context['enunciado_active'] = 'active'
            context['casos_active'] = ''
            context['resultados_active'] = ''
        elif self.tab == 'casos':
            context['enunciado_active'] = ''
            context['casos_active'] = 'active'
            context['resultados_active'] = ''
        else:
            context['enunciado_active'] = ''
            context['casos_active'] = ''
            context['resultados_active'] = 'active'

        if self.kwargs['result'] == 1:
            feedback = Feedback.objects.filter(user = self.request.user, problema=problema).order_by('fecha_envio').last()
            context['test_feedback'] = TestFeedback.objects.filter(feedback=feedback)
            context['cantidad_buenos'] = context['test_feedback'].filter(passed='True').count()
            context['cantidad_malos'] = context['test_feedback'].filter(passed='False').count()
            context['ordered_test_feedback'] = get_ordered_test_feedback(context['test_feedback'], problema)
            context['resultados_active'] = "active"
        return context

    def get(self, request, *args, **kwargs):

        context = self.get_context_data(**kwargs)
        curso_id = kwargs['curso_id']
        curso = get_cursos(request.user, curso_id)

        if curso == None:
            messages.success(request, "No tienes permiso para ingresar a este curso")
            return HttpResponseRedirect(reverse('usuarios:index'))

        problema_id = kwargs['problema_id']

        if not problema_en_curso(problema_id, curso_id):
            messages.success(request, "No tienes permiso para ver ese problema")
            return HttpResponseRedirect(reverse('usuarios:index'))

        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):

        # Get assignment and post data
        problema = get_object_or_404(Problema, id=self.kwargs['problema_id'])
        curso = get_object_or_404(Curso, id=self.kwargs['curso_id'])

        if not bool(problema.tests):
            return self.handle_failed_single_response(request,
                                                      "The Assignment has no tests, talk to the course's teacher or assistants to fix this issue.",
                                                      **kwargs)

        data = request.POST.copy()

        # Get language and file from data
        lang = 'cpp'
        file = request.FILES.get('sample_code')  # Archivo que quiero testear

        # If the user didn´t uploaded a file it sends the user back to the same page
        if file is None or file.name.split('.')[-1] != 'cpp':
            context_data = self.get_context_data(**kwargs)
            context_data['file_error'] = "Debes agregar un archivo" if (
                    file is None) else "El archivo debe ser formato .cpp"
            return render(request, self.template_name, context_data)

        # Save the file in the media folder
        fs = FileSystemStorage()
        filename = fs.save(file.name, file)

        # get the path from the media folder
        script_path = settings.MEDIA_ROOT + '/' + filename
        test_path = problema.tests.path.replace("\\", "/")

        # Send and receive data for testing.
        response = ComunicationClient.send_submission(script_path, test_path, lang)

        compiled_file = filename.split('.')[0]

        try:
            # Delete compiled file
            os.remove(compiled_file)
        except:
            pass

        if response[0] == "success":
            os.remove(script_path)
            return self.handle_successful_single_response(request, problema, response[1], file, **kwargs)
        else:
            # os.remove(script_path)
            return self.handle_failed_single_response(request, response[1], **kwargs)

    def handle_successful_single_response(self, request, problema, tests_arr, codigo_solucion, **kwargs):
        # Save tests_arr as a feedback object and a group of simple_test_feedback objects
        feedback_user = request.user
        feedback_problema = problema
        feedback_codigo = codigo_solucion
        feedback = Feedback.objects.create(user=feedback_user, problema=feedback_problema,
                                           codigo_solucion=feedback_codigo)
        self.crear_test_feedbacks(feedback, tests_arr)

        this_context = self.get_context_data(**kwargs)
        this_context['test_feedback'] = TestFeedback.objects.filter(feedback=feedback)
        this_context['ordered_test_feedback'] = get_ordered_test_feedback(this_context['test_feedback'], problema)
        this_context['cantidad_buenos'] = this_context['test_feedback'].filter(passed='True').count()
        this_context['cantidad_malos'] = this_context['test_feedback'].filter(passed='False').count()
        this_context['test_array'] = tests_arr
        this_context['resultados_active'] = "active"
        this_context['enunciado_active'] = ""
        this_context['casos_active'] = ""
        return render(request, self.feedback_template_name, this_context)

    def crear_test_feedbacks(self, feedback, tests_arr):
        nuevos_outputs = {}
        for test in tests_arr:
            input = test[1]
            caso = Caso.objects.filter(input=input, problema=feedback.problema).first()
            test_feedback = TestFeedback.objects.create(passed=test[0], output_obtenido=test[5], error=test[4],
                                                        caso=caso,
                                                        feedback=feedback)

            # Si no pasa el test y no tuvo error, tengo que agregar output_alternativo y asociárselo al test_feedback
            if test_feedback.passed == 0 and test_feedback.error == 0:
                feedback.resultado = False
                feedback.save()
                output_alternativo, created = OutputAlternativo.objects.get_or_create(caso=caso,
                                                                                      output_obtenido=test_feedback.output_obtenido)
                if not created:
                    output_alternativo.frecuencia += 1
                    output_alternativo.save()

                test_feedback.output_alternativo = output_alternativo
                test_feedback.save()

    '''
    Los errrores serían si no hay tests o si no compila el código. 
    '''

    def handle_failed_single_response(self, request, error, **kwargs):
        this_context = self.get_context_data(**kwargs)
        this_context['error'] = error
        this_context['error_resumen'] = "Hubo un error al procesar tu código"
        this_context['resultados_active'] = "active"
        this_context['enunciado_active'] = ""
        return render(request, self.feedback_template_name, this_context)


@method_decorator([profesora_required], name='dispatch')
class CrearProblemasViews(LoginRequiredMixin, View):
    def get(self, request, **kwargs):
        clase_id = kwargs['clase_id']
        clase = get_object_or_404(Clase.objects.filter(id=clase_id))

        if not request.user in clase.curso.profesoras.all():
            messages.success(request, "No tienes permiso para ingresar a este curso")
            return HttpResponseRedirect(reverse('usuarios:index'))

        form = ProblemaForm()
        return render(request, 'problemas/crear_problema.html', {'clase': clase, 'form': form})

    def post(self, request, **kwargs):
        clase_id = kwargs['clase_id']
        clase = get_object_or_404(Clase.objects.filter(id=clase_id))
        if not request.user in clase.curso.profesoras.all():
            messages.success(request, "No tienes permiso para ingresar a este curso")
            return HttpResponseRedirect(reverse('usuarios:index'))

        form = ProblemaForm(request.POST, request.FILES)
        if form.is_valid():
            nuevo_problema = form.save()
            nuevo_problema.clase = clase
            nuevo_problema.save()

problemas/templates/problemas/casos_prueba.html
{% load template_tags %}
<ul class="collapsible expandable">
    {% for categoria in casos %}
        <li id="casos-categoria">
            <div class="collapsible-header" style="justify-content: space-between">
                <span> <i class="material-icons">expand_more</i>{{ categoria.categoria }}</span>

                    {% with nuevos_outputs|output_exists:categoria.casos as outputs_cat %}
                        {% if outputs_cat == 1 %}
                            <span class="big-badge">{{  nuevos_outputs|output_exists:categoria.casos }} nuevo output</span>
                        {% elif outputs_cat > 1 %}
                            <span class="big-badge">{{  nuevos_outputs|output_exists:categoria.casos }} nuevos outputs</span>
                        {% endif %}
                    {% endwith %}

            </div>
            <div class="collapsible-body">
                <div style="max-width: 100%; overflow-x:auto">
                    <table id="casos-de-prueba" class="data-feedback" >
                        <thead>
                            <tr class="row_good_feedback">
                                <th>Input</th>
                                <th>Output esperado</th>
                                <th>Casos alternativos</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for caso in categoria.casos %}
                                <tr class="row_good_feedback">
                                    <td class="consolas">{{ caso.input }}</td>
                                    <td class="consolas">{{ caso.output_esperado }}</td>
                                    <td>
                                        {% with nuevos_outputs|lookup:caso.id as nuevos %}
                                            {% if nuevos > 0  %}

                                                <button class="open-modal btn btn-small notification" id="{{ caso.id }}">
                                                    <span>Ver</span>
                                                    <span class="badge" id="num-notif"> {{ nuevos_outputs | lookup:caso.id }}</span>
                                                </button>

                                            {% else %}
                                                <button class="open-modal btn btn-small notification" id="{{ caso.id }}">
                                                    <span>Ver</span>
                                                </button>
                                            {% endif %}
                                        {% endwith %}
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </li>
        {% for caso in categoria.casos  %}
            <div id="modal_div_{{ caso.id }}"></div>

        {% endfor %}
    {% endfor %}
</ul>

{%  block scripts %}
    <script>

        $(document).on('click', '.open-modal', function () {
            var id = $(this)[0].id
            var modalDiv = $('#modal_div_' + id)
            $.ajax({
                url:'{% url 'feedback:casos-alternativos' %}',
                data:{
                    'id':id,
                },
                success:function (data) {
                    modalDiv.html(data)
                    mi_modal = $('#output_alternativo_'+ id)
                    mi_modal.modal();
                    mi_modal.modal('open')
                },
                error:function(){
                    console.log('hubo un error con el ajax')
                }
            })
        })
    </script>

{% endblock %}

problemas/templates/problemas/crear_problema.html
{% extends 'menu.html' %}
{% load static %}


{% block title %}{{ curso.nombre }}{% endblock %}

{% block content %}
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
<div class="container">

    <h1>Crear problema</h1>
        <div class="row">
            <form method="post" class="col s12" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                    <div class="input-field col s6">
                        {{ form.titulo }}
                        {{ form.titulo.errors }}
                        <label>Título del problema</label>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group">
                       <label for="id_statement"><strong>Enunciado</strong></label>
                        {{ form.statement}}
                        <small>Solo se aceptan PDF's</small>
                    </div>
                </div>
                <div class="row alinear-centro-v" style="margin-top: 3%">
                    <span class="espacio-derecha">Descargar ejemplos de casos de prueba:</span>
                    <a href="{% static 'file_samples/ejemplo_caso.json' %}" class="btn btn-small btn-no-bg espacio-derecha"
                       download="ejemplo_caso.json"><i class="material-icons left">get_app</i> Formato .json</a>
                    <a href="{% static 'file_samples/ejemplo_caso.csv' %}" class="btn btn-small btn-no-bg"
                       download="ejemplo_caso.csv"><i class="material-icons left">get_app</i> Formato .csv</a>
                </div>
                <div class="row">
                     <div class="form-group">
                         <label><strong>Casos de prueba</strong></label>
                        {{ form.tests }}
                        <small>Se aceptan formatos .csv y .json</small>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12">
                        <button type="submit" class="waves-effect waves-light btn-medium btn" >Crear problema</button>
                        <a href="{% url 'cursos:curso' curso_id=clase.curso.id %}" class="waves-effect waves-light btn-medium btn">Cancelar</a>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

problemas/templates/problemas/editar_problema.html
{% extends 'menu.html' %}
{% load static %}


{% block title %}{{ curso.nombre }}{% endblock %}

{% block content %}
    <div class="container">

        <h1>Editar problema</h1>
        <div class="row">
            <form method="post" class="col s12" enctype="multipart/form-data">
                {% csrf_token %}
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
                <div class="row">
                    <div class="input-field col s6">
                        {{ form.titulo }}
                        {{ form.titulo.errors }}
                        <label>Título del problema</label>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group">
                       <label for="id_statement"><strong>Enunciado</strong></label>
                        {{ form.statement}}
                        <small>Solo se aceptan PDF's</small>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12">
                        <button type="submit" class="waves-effect waves-light btn-medium btn" >Guardar cambios</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

problemas/templates/problemas/enunciado_problema.html
{% load static %}

<div class="row">
    <div class="col s8 ">
        {% if problema.statement %}
            <object data="{{ problema.statement.url }}" type="application/pdf"
                    width="100%" height="1000">
                <p>Something happened</p>
            </object>
        {% else %}
            <p>This problema doesn't have a statement.</p>
        {% endif %}
    </div>
    <div class="col s4 ">
        <div class="card horizontal">
            <div class="card-content">
                <span class="card-title">Subir solución</span>

                <div class="card-action">
                    {% if file_error %}
                        <div class="alert">
                            <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                            {{file_error}}
                        </div>
                    {% endif %}
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class = "file-field input-field">
                                <div class = "btn btn-small">
                                    <span>Seleccionar</span>
                                    <input type = "file" name="sample_code" id="file"/>
                                </div>

                                <div class = "file-path-wrapper">
                                    <input class = "file-path validate" type = "text"
                                           placeholder = "Seleccionar archivo" />
                                </div>
                            </div>

                            <small>Solo se acepta formato .cpp</small>
                        </div>

                        <div class="input-field row">
                            <button class="waves-effect waves-light btn btn-small" id="submit-sol" type="submit" disabled>Subir</button>
                        </div>
                    </form>
                </div>

            </div>
        </div>

    </div>
</div>

<script>
        let showMessage = () => {
            $('#cover, #message').css('display', 'block');
        };
    </script>

problemas/templates/problemas/envios_anteriores.html
{% load static %}
<h1>Envíos anteriores</h1>

problemas/templates/problemas/feedback_error.html
{% extends 'menu.html' %}
{% load static %}
{% block title %}{{ curso.nombre }}{% endblock %}


{% block content %}
    <h1>{{ curso.nombre }}</h1>
    ERROR CON EL FEEDBACK
    {{ error }}
{% endblock %}

problemas/templates/problemas/feedback_page_tabla.html
    {% if test_feedback %}
    <div style="display: flex; justify-content: space-between">

        <blockquote>Casos aprobados: {{ cantidad_buenos }} <br>
        Casos no aprobados: {{ cantidad_malos }}</blockquote>

    </div>


        <table id="tabla-feedback" class="cell-border" >
            <thead>
                <tr>
                    <th>Descripción</th>
                    <th>Input</th>
                    <th>Output esperado</th>
                    <th>Output obtenido</th>
                    <th>Resultado</th>
                </tr>
            </thead>
            <tbody>
                {% for test in test_feedback %}
                    <tr>
                        <td>{{ test.caso.descripcion }}</td>
                        <td>{{test.caso.input }}</td>
                        <td>{{test.caso.output_esperado }}</td>
                        <td >{{test.output_obtenido }}</td>
                        {% if test.passed %}
                            <td>  <i class="material-icons icon-green">check_circle</i> </td>
                        {% else %}
                          <td>  <i class="material-icons icon-red">cancel</i> </td>
                        {% endif %}
                    </tr>

                {% endfor %}
            </tbody>
        </table>



    {% else %}
        No se han enviado soluciones aún.

    {% endif %}

problemas/templates/problemas/inicio_problemas.html
{% extends 'menu.html' %}
{% load static %}
{% block title %}{{ curso.nombre}} : {{ problema.titulo }}{% endblock %}

{% block content %}
    <div class="title-and-button">
            <h3>{{ problema.titulo }}</h3>
            {% if request.user.es_profesora %}
                <a href="{% url 'problemas:editar-problema' curso_id=curso.id problema_id=problema.id %}" class="btn btn-primary btn-large">Editar<i class="material-icons left">mode_edit</i></a>
            {% endif %}
    </div>
    <h4>{{ curso.nombre }}</h4>

    <a href="{% url 'cursos:curso' curso_id=curso.id %}" style="margin-bottom:1rem;" class="waves-effect waves-light btn-small btn">
                        <i class="material-icons left">arrow_back</i>Volver</a>
    <!-- Tabs del problema-->
 <ul class="tabs tabs-fixed-width tab-demo z-depth-1">
    <li class="tab"><a class="{{ enunciado_active }}" href="#enunciado">Enunciado</a></li>
     {% if request.user.es_profesora or request.user.es_voluntaria %}
        <li class="tab"><a class="{{ casos_active }}" href="#casos">Casos de prueba</a> </li>
    {% endif %}
    <li class="tab"><a class="{{ resultados_active }}" href="#resultados">Mi feedback</a></li>

  </ul>
  <div id="enunciado" class="col s12 tab_content">{% include "problemas/enunciado_problema.html" %}</div>
  <div id="resultados" class="col s12 tab_content">
      {%  if error %}
          {% include "error.html" %}
      {% else %}
        {% include "problemas/feedback_page.html" %}
      {% endif %}
  </div>
    {% if request.user.es_profesora or request.user.es_voluntaria %}
        <div id="casos" class="col s12 tab_content">{% include "problemas/casos_prueba.html" %}</div>
    {% endif %}
{% endblock %}