NiñasProject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

import usuarios

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("usuarios.urls")),
    path('', include("cursos.urls")),
    path('coordinadora/', include("coordinacion.urls", namespace='coordinacion')),
    path('', include("asistencia.urls")),
    path('',include("problemas.urls")),
    path('',include("clases.urls")),
    path('',include("feedback.urls")),
] +static(settings.MEDIA_URL, document_ROOT=settings.MEDIA_ROOT)

clases/urls.py
from django.urls import path, include

from clases import views

app_name = 'clases'
urlpatterns = [
    path('<int:curso_id>/agregar-clase/', views.CrearClaseView.as_view(), name='agregar_clase'),
]

coordinacion/urls.py
from django.urls import path, include

from coordinacion import views

app_name = 'coordinadora'
urlpatterns = [
    path('inicio/', views.CoordinadoraInicioView.as_view(), name='inicio_coordinadora'),
    path('cursos', views.CoordinadoraCursosView.as_view(), name='cursos'),
    path('cursos/crear', views.CoordinadoraCrearCursosView.as_view(), name='crear_curso'),
    path('cursos/editar/<int:curso_id>', views.CoordinadoraEditarCursosView.as_view(), name='editar_curso'),
    path('cursos/eliminar/<int:curso_id>', views.eliminar_curso , name='eliminar_curso'),
    path('curso/eliminar_cursos', views.eliminar_cursos, name='eliminar_cursos'),
    path('users', views.CoordinadoraUsersView.as_view(), name = 'users'),
    path('users/crear', views.CoordinadoraCrearUserView.as_view(), name = 'crear_user'),
    path('users/editar/<int:user_id>', views.CoordinadoraEditarUsersView.as_view(), name = 'editar_users'),
    path('users/eliminar/<int:user_id>', views.eliminar_user, name = 'eliminar_user'),
    path('users/eliminar_users', views.eliminar_users, name = 'eliminar_users')
]

coordinacion/models.py
from django.db import models

# Create your models here.
from usuarios.models import User


class Sede(models.Model):
    nombre = models.CharField(max_length=100, default="Sede", primary_key=True)
    profesoras = models.ManyToManyField(User, related_name="sedes_profesoras", blank=True)
    voluntarias = models.ManyToManyField(User, related_name="sedes_voluntarias", blank=True)
    alumnas = models.ManyToManyField(User, related_name="sedes_alumnas", blank=True)
    coordinadora = models.ForeignKey(User, related_name="sedes_coordinadora", null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.nombre

coordinacion/forms.py
from django.forms import ModelForm

from django.forms.widgets import CheckboxInput
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator

from cursos.models import Curso
from usuarios.models import User

from django import forms


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'es_profesora','es_alumna','es_voluntaria']

class CursoForm(ModelForm):
    lista_alumnas = forms.FileField(required=False, help_text="Solo se acepta formato csv",validators=[FileExtensionValidator(['json', 'csv'])])
    class Meta:
        model = Curso
        fields = ['nombre', 'profesoras', 'voluntarias', 'alumnas']

coordinacion/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.utils.decorators import method_decorator
from NiñasProject.decorators import coordinadora_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.edit import UpdateView, CreateView, FormView
from django.contrib import messages
from coordinacion.forms import UserForm, CursoForm
from django.core.exceptions import ValidationError
from usuarios.management.commands.crear_users import Command
from my_lib.files_wrapper import create_temp_file
from django.core.files import File

import os
import csv
import datetime

from coordinacion.models import Sede
from cursos.models import Curso
from usuarios.models import User
# Create your views here.
from django.views import View

@method_decorator([coordinadora_required], name='dispatch')
class CoordinadoraInicioView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'coordinacion/inicio_coordinadora.html')

# CURSOS VIEWS
@method_decorator([coordinadora_required], name='dispatch')
class CoordinadoraCursosView(LoginRequiredMixin, View):
    def get(self, request):
        cursos = Curso.objects.all()
        return render(request, 'coordinacion/cursos/cursos.html', {'cursos':cursos})

@method_decorator([coordinadora_required], name='dispatch')
class CoordinadoraEditarCursosView(LoginRequiredMixin, UpdateView):
    model = Curso
    fields = ('nombre', 'profesoras', 'voluntarias', 'alumnas')
    template_name = 'coordinacion/cursos/editar_curso.html'
    pk_url_kwarg = 'curso_id'
    context_object_name = 'curso'
    
    def get_form(self):
        form = super().get_form()
        sede = Sede.objects.get(coordinadora=self.request.user)
        form.fields['profesoras'].queryset = sede.profesoras.filter(es_profesora=True, is_active=True)
        form.fields['alumnas'].queryset = sede.alumnas.filter(es_alumna=True, is_active=True)
        form.fields['voluntarias'].queryset = sede.voluntarias.filter(es_voluntaria=True, is_active=True)
        return form

    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'Curso modificado')
        return HttpResponseRedirect(reverse('coordinacion:cursos'))

@method_decorator([coordinadora_required], name='dispatch')
class CoordinadoraCrearCursosView(LoginRequiredMixin, CreateView):
    # model = Curso
    # fields = ('nombre', 'sede', 'profesoras', 'voluntarias', 'alumnas')
    template_name = 'coordinacion/cursos/crear_curso.html'
    context_object_name = 'curso'

    def get_form(self):
        form = CursoForm()
        sede = Sede.objects.get(coordinadora=self.request.user)
        form.fields['nombre'].initial = ""
        form.fields['profesoras'].queryset = sede.profesoras.filter(es_profesora=True, is_active=True)
        form.fields['alumnas'].queryset = sede.alumnas.filter(es_alumna=True, is_active=True)
        form.fields['voluntarias'].queryset = sede.voluntarias.filter(es_voluntaria=True, is_active=True)
        return form

    def post(self, request, *args, **kwargs):
        try:
            filename = self.validate(request)
        except Exception as e:
            messages.success(request, e)
            return HttpResponseRedirect(reverse('coordinacion:crear_curso'))
        self.form_valid(request, filename)
        messages.success(self.request, 'Curso creado')
        return HttpResponseRedirect(reverse('coordinacion:cursos'))


    def validate(self, request):
        user = request.user
        form = request.POST
        sede = Sede.objects.get(coordinadora=user)
        if len(Curso.objects.filter(nombre=form['nombre'], anho = datetime.datetime.now().year, sede=sede.nombre))>0:
            raise ValidationError("Ya existe un curso con este nombre este año en esta sede")
        lista = request.FILES.get('lista_alumnas')
        if lista!=None:
            filename = create_temp_file(File(lista), 'csv')
            with open(filename, 'r') as lista:
                try:
                    Command().csvValidator(lista)
                except Exception as e:
                    if os.path.exists(filename):
                        os.remove(filename)
                    raise e
            return filename
        else:
            return None

    def form_valid(self, request, filename):
        form = request.POST
        user = request.user
        sede = Sede.objects.get(coordinadora=user)
        curso = Curso.objects.create(nombre=form.get('nombre'), sede=sede)
        for profesora in form.getlist('profesoras'):
            curso.profesoras.add(profesora)
        if filename!=None:
            with open(filename, 'r', encoding='utf-8-sig') as csvFile:
                Command().create('alumnas', sede, curso, csvFile)
            if os.path.exists(filename):
                os.remove(filename)
        for alumna in form.getlist('alumnas'):
            if not curso.alumnas.filter(id=alumna).exists():
                curso.alumnas.add(alumna)
        for voluntaria in form.getlist('voluntarias'):
            curso.voluntarias.add(voluntaria)
        curso.save()


@coordinadora_required
def eliminar_curso(request, curso_id):
    Curso.objects.get(id=curso_id).delete()
    return HttpResponseRedirect(reverse('coordinacion:cursos'))

@coordinadora_required
def eliminar_cursos(request):
    cursos_id = request.POST.getlist('cursos_delete')
    for curso_id in cursos_id:
        Curso.objects.get(id=curso_id).delete()
    messages.success(request, 'Cursos eliminados')
    return HttpResponseRedirect(reverse('coordinacion:cursos'))

#USERS VIEWS

@method_decorator([coordinadora_required], name='dispatch')
class CoordinadoraUsersView(LoginRequiredMixin, View):
    def get(self, request):
        sede = Sede.objects.get(coordinadora=self.request.user)
        profesoras = sede.profesoras.filter(es_profesora=True, is_active=True)
        alumnas = sede.alumnas.filter(es_alumna=True, is_active=True)
        voluntarias = sede.voluntarias.filter(es_voluntaria=True, is_active=True)
        return render(request, 'coordinacion/users/users_index.html', {'profesoras':profesoras, 'alumnas':alumnas, 'voluntarias':voluntarias})

@method_decorator([coordinadora_required], name='dispatch')
class CoordinadoraEditarUsersView(LoginRequiredMixin, UpdateView):
    model = User
    fields = ('first_name', 'last_name', 'es_alumna', 'es_voluntaria', 'es_profesora')
    template_name = 'coordinacion/users/editar_user.html'
    pk_url_kwarg = 'user_id'
    context_object_name = 'user'

    def form_valid(self, form):
        user = form.save()
        sede = Sede.objects.get(coordinadora=self.request.user)
        sede.profesoras.remove(user)
        sede.voluntarias.remove(user)
        sede.alumnas.remove(user)
        if user.es_voluntaria:
            sede.voluntarias.add(user)
        if user.es_profesora:
            sede.profesoras.add(user)
        if user.es_alumna:
            sede.alumnas.add(user)

        messages.success(self.request, 'Usuaria modificada')
        return HttpResponseRedirect(reverse('coordinacion:users'))

@method_decorator([coordinadora_required], name='dispatch')
class CoordinadoraCrearUserView(LoginRequiredMixin, FormView):
    form_class = UserForm
    template_name = 'coordinacion/users/crear_user.html'

    def form_valid(self, form):
        data = form.cleaned_data
        user = User.objects.create_user(first_name=data['first_name'], last_name=data['last_name'], username=data['username'],
               password='tempPass21', es_profesora=data['es_profesora'], es_alumna=data['es_alumna'], es_voluntaria=data['es_voluntaria'])
        user.save()
        sede = Sede.objects.get(coordinadora=self.request.user)
        if data['es_profesora']:
            sede.profesoras.add(user)
        if data['es_voluntaria']:
            sede.voluntarias.add(user)
        if data['es_alumna']:
            sede.alumnas.add(user)
        messages.success(self.request, 'Usuaria Creada')
        return HttpResponseRedirect(reverse('coordinacion:users'))

@coordinadora_required
def eliminar_user(request, user_id):
    user = User.objects.get(id=user_id)
    user.is_active = False
    user.save()
    return HttpResponseRedirect(reverse('coordinacion:users'))

@coordinadora_required
def eliminar_users(request):
    users_id = request.POST.getlist('user_delete')
    for user_id in users_id:
        user = User.objects.get(id=user_id)
        user.is_active = False
        user.save()
    messages.success(request, 'Usuarias eliminadas')
    return HttpResponseRedirect(reverse('coordinacion:users'))

coordinacion/templates/coordinacion/users/crear_user.html
{% extends 'menu.html' %}
{% load static %}
{% block title %}Crear Usuaria{% endblock %}


{% block content %}

<h2 style="text-align: center;">Crear Usuaria</h2>
<form method="post">
    {% csrf_token %}
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
    <div class="fieldWrapper">
        <label for="{{ form.first_name.id_for_label }}">Nombre</label>
        {{ form.first_name }}
        {{form.first_name.errors}}
    </div>
    <div class="fieldWrapper">
        <label for="{{ form.last_name.id_for_label }}">Apellido</label>
        {{ form.last_name }}
        {{ form.last_name.errors }}

    </div>
    <div class="fieldWrapper">
        <label for="{{ form.username.id_for_label }}">Nombre de usuario</label>
        {{ form.username }}
        {{ form.username.errors }}
    </div>

    <div class="flex-container-asistencia">
    <label class="nombre-checkbox">
        {{ form.es_profesora }}
        
        <span>Es profesora</span>
    </label>
    </div>

    <div class="flex-container-asistencia">
        <label class="nombre-checkbox">
            {{ form.es_voluntaria }}
            <span>Es voluntaria</span>
        </label>
    </div>


    <div class="flex-container-asistencia">
        <label class="nombre-checkbox">
            {{ form.es_alumna }}
            <span>Es alumna</span>
        </label>
    </div>

    <div>
        <a href="{% url 'coordinacion:inicio_coordinadora' %}" class="waves-effect waves-light btn-small btn red accent-2" >
            <i class="material-icons left">arrow_back</i>Volver</a>

            <button type="submit" class="waves-effect waves-light btn-small btn red accent-2">
                <i class="material-icons right">playlist_add_check</i>Guardar</button>

    </div>
</form>
{% endblock %}

coordinacion/templates/coordinacion/users/editar_user.html
{% extends 'menu.html' %}
{% load static %}
{% block title %}Editar Usuaria{% endblock %}


{% block content %}
<h2 style="text-align: center;">Editar Usuaria</h2>

<form method="post">
    {% csrf_token %}

    <div class="fieldWrapper">
        <label for="{{ form.first_name.id_for_label }}">Nombre</label>
        {{ form.first_name }}
    </div>
    <div class="fieldWrapper">
        <label for="{{ form.last_name.id_for_label }}">Apellido</label>
        {{ form.last_name }}
    </div>

    <div class="flex-container-asistencia">
    <label class="nombre-checkbox">
        {{ form.es_profesora }}
        <span>Es profesora</span>
    </label>
    </div>

    <div class="flex-container-asistencia">
        <label class="nombre-checkbox">
            {{ form.es_voluntaria }}
            <span>Es voluntaria</span>
        </label>
    </div>


    <div class="flex-container-asistencia">
        <label class="nombre-checkbox">
            {{ form.es_alumna }}
            <span>Es alumna</span>
        </label>
    </div>

    <div>
        <a href="{% url 'coordinacion:users' %}" class="waves-effect waves-light btn-small btn red accent-2" >
            <i class="material-icons left">arrow_back</i>Volver</a>

            <button type="submit" class="waves-effect waves-light btn-small btn red accent-2">
                <i class="material-icons right">playlist_add_check</i>Guardar</button>
    </div>

</form>
{% endblock %}

coordinacion/templates/coordinacion/users/users_index.html
{% extends 'menu.html' %}
{% load static %}
{% block title %}Coordinacion usuarias{% endblock %}


{% block content %}
{% if alumnas or profesoras or voluntarias %}
<h1>Coordinación usuarias</h1>
<div class="left">
  <a href="{% url 'coordinacion:crear_user' %}" class="waves-effect waves-light btn-small btn red accent-2">
    <i class="material-icons right">add</i>Crear</a>
</div>

<form method="post" action="{% url 'coordinacion:eliminar_users'%}" onsubmit="return eliminar_alerta('¿Esta segura que desea eliminar a estas usuarias?')" >
  {%csrf_token%}
  <div class="right" style="margin-bottom: 10px;">
    <button id="btn-1" type="submit" class="waves-effect waves-light btn-small btn red accent-2 btn-right" disabled>
      <i class="material-icons right">playlist_add_check</i>Eliminar Usuarias</button>
    </div>
  <br>
  <br>
<ul class="collapsible expandable">
  <li >
    <div class="collapsible-header">
      <i class="material-icons">expand_more</i>
      Alumnas
  </div>
  <div class="collapsible-body">
  <div class="container-tabla-users">
    <table id="alumnas_table" class="display tabla-asist-gral">
      <thead>
        <tr>
          <th></th>
          <th>Nombre</th>
          <th>Apellido</th>
          <th>Nombre de Usuaria</th>
        </tr>
      </thead>
      <tbody>
        {% for alumna in alumnas %}
        <tr>
          <td>
            <label>
              <input type="checkbox" id="{{alumna.first_name}} {{alumna.last_name}}" value={{alumna.id}} name=user_delete onclick="clicked(this.checked, this.id)" />
              <span></span>
            </label>
          </td>
          <td>{{alumna.first_name}}</td>
          <td>{{alumna.last_name}}</td>
          <td><a href="{% url 'coordinacion:editar_users' alumna.id %}">{{alumna.username}}</a></td>
        </tr>
        {%endfor%}
      </tbody>
    </table>
    </div>
  </div>
  </li>

  <li>
    <div class="collapsible-header">
      <i class="material-icons">expand_more</i>
      Profesoras
  </div>
  <div class="collapsible-body">
  <div class="container-tabla-users">
    <table id="profesoras_table" class="display tabla-asist-gral">
      <thead>
        <tr>
          <th></th>
          <th>Nombre</th>
          <th>Apellido</th>
          <th>Nombre de Usuaria</th>
        </tr>
      </thead>
      <tbody>
        {% for profesora in profesoras %}
        <tr>
          <td>
            <label>
              <input type="checkbox" value={{profesora.id}} id="{{profesora.first_name}} {{profesora.last_name}}" name=user_delete onclick="clicked(this.checked, this.id)" />
              <span></span>
            </label>
          </td>
          <td>{{profesora.first_name}}</td>
          <td>{{profesora.last_name}}</td>
          <td><a href="{% url 'coordinacion:editar_users' profesora.id %}">{{profesora.username}}</a></td>
        </tr>
        {%endfor%}
      </tbody>
    </table>
  </div>
  </div>
  </li>

  <li>
    <div class="collapsible-header">
      <i class="material-icons">expand_more</i>
      Voluntarias
  </div>
  <div class="collapsible-body">
  <div class="container-tabla-users">
    <table id="voluntarias_table" class="display tabla-asist-gral" ">
      <thead>
        <tr>
          <th></th>
          <th>Nombre</th>
          <th>Apellido</th>
          <th>Nombre de Usuaria</th>
        </tr>
      </thead>
      <tbody>
        {% for voluntaria in voluntarias %}
        <tr >
          <td>
            <label>
              <input type="checkbox" value={{voluntaria.id}} id="{{voluntaria.first_name}} {{voluntaria.last_name}}" name=user_delete onclick="clicked(this.checked, this.id)" />
              <span></span>
            </label>
          </td>
          <td>{{voluntaria.first_name}}</td>
          <td>{{voluntaria.last_name}}</td>
          <td><a href="{% url 'coordinacion:editar_users' voluntaria.id %}">{{voluntaria.username}}</a></td>
        </tr>
        {%endfor%}
      </tbody>
    </table>
  </div>
  </div>
  </li>
</ul>

<div class="left">
  <a href="{%url 'coordinacion:inicio_coordinadora'%}" class="waves-effect waves-light btn-small btn red accent-2" >
    <i class="material-icons left">arrow_back</i>Volver</a>
</div>
<div class="right">
  <button id="btn-2" type="submit" class="waves-effect waves-light btn-small btn red accent-2" style="margin-bottom: 10px;" disabled>
      <i class="material-icons right">playlist_add_check</i>Eliminar Usuarias</button>
</div>
</form>

{%else%}
<h2 style="text-align: center;"> No hay usuarias en esta sede </h2>
<div class="center">
  <a href="{%url 'coordinacion:inicio_coordinadora'%}" class="waves-effect waves-light btn-small btn red accent-2" >
    <i class="material-icons left">arrow_back</i>Volver</a>
  <a href="{% url 'coordinacion:crear_user' %}" class="waves-effect waves-light btn-small btn red accent-2">
    <i class="material-icons right">add</i>Crear</a>
  </div>
{%endif%}
{% endblock %}
{% block scripts %}
    <script src={% static 'js/scripts.js' %}></script>
{% endblock %}