NiñasProject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

import usuarios

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("usuarios.urls")),
    path('', include("cursos.urls")),
    path('coordinadora/', include("coordinacion.urls", namespace='coordinacion')),
    path('', include("asistencia.urls")),
    path('',include("problemas.urls")),
    path('',include("clases.urls")),
    path('',include("feedback.urls")),
] +static(settings.MEDIA_URL, document_ROOT=settings.MEDIA_ROOT)

asistencia/urls.py
import cursos
from django.urls import path
from .views import get_form, clear_cache
from asistencia import views
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static

app_name = 'asistencia'

urlpatterns = [
    path('<int:curso_id>/asistencia/', views.Asistencia_GralView.as_view(), name='asistencia_gral'),
    path('<int:curso_id>/asistencia/<int:clase_id>/', get_form, name='asistencia'),
    path('<int:curso_id>/asistencia/<int:clase_id>/cache', clear_cache, name="asistencia_cache")
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clases/urls.py
from django.urls import path, include

from clases import views

app_name = 'clases'
urlpatterns = [
    path('<int:curso_id>/agregar-clase/', views.CrearClaseView.as_view(), name='agregar_clase'),
]

cursos/urls.py
from django.urls import path, include

from cursos import views

app_name = 'cursos'
urlpatterns = [
    path('<int:curso_id>/curso/', views.CursoView.as_view(), name='curso'),
    path('<int:curso_id>/curso/<str:order>/', views.CursoView.as_view(), name='curso'),
    path('mis_cursos/', views.MisCursosView.as_view(), name='mis_cursos'),
    path('<int:curso_id>/estadisticas/', views.EstadisticasView.as_view(), name='estadisticas'),

]

problemas/urls.py
import cursos
from django.urls import path
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static

from problemas import views

app_name = 'problemas'

urlpatterns = [
    path('<int:curso_id>/curso/<int:problema_id>/problema/enunciado/<int:result>', views.ProblemasViews.as_view(tab='enunciado'), name='enunciado-problema'),
    path('<int:curso_id>/curso/<int:problema_id>/problema/casos/<int:result>', views.ProblemasViews.as_view(tab='casos'), name='casos-problema'),
    path('<int:curso_id>/curso/<int:problema_id>/problema/feedback/<int:result>', views.ProblemasViews.as_view(tab='feedback'), name='feedback-problema'),
    path('<int:clase_id>/agregar-problema', views.CrearProblemasViews.as_view(), name='crear-problema'),
    path('<int:curso_id>/curso/<int:problema_id>/problema/edit/', views.EditarProblemasViews.as_view(), name='editar-problema')
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path, include

from usuarios import views

app_name = 'usuarios'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('reset-password/', views.ResetPassword.as_view(),name='reset-password')
]

cursos/models.py
from django.db import models
import datetime

# Create your models here.
from usuarios.models import User
from coordinacion.models import Sede

class Tema(models.Model):
    nombre = models.CharField(max_length=50)


class Curso(models.Model):
    class Meta:
        unique_together = (('nombre', 'anho', 'sede'),)

    nombre = models.CharField(max_length=100, default="curso_default")
    profesoras = models.ManyToManyField(User, related_name="profesoras", blank=True)
    voluntarias = models.ManyToManyField(User, related_name="voluntarias", blank=True)
    alumnas = models.ManyToManyField(User, related_name="alumnas", blank=True)
    tema = models.ManyToManyField(Tema, related_name="tags", blank=True)
    cant_clases = models.IntegerField(default=1)
    anho = models.IntegerField(default=datetime.datetime.now().year)
    sede = models.ForeignKey(Sede, on_delete=models.CASCADE, to_field="nombre", blank=True, null=True)

    def __str__(self):
        return self.nombre

problemas/models.py
import os
import json
from django.conf import settings
from django.core.validators import FileExtensionValidator
from django.db import models

from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils import timezone
from django.core.files import File

from clases.models import Clase
from my_lib.files_wrapper import file_to_file, change_path_extension, get_file_name, check_if_file_is_valid


class Problema(models.Model):
    titulo = models.CharField(max_length=100)
    fecha_creacion = models.DateTimeField(editable=False, blank=True, null=True)

    statement = models.FileField(upload_to='statements', help_text="Solo se aceptan PDF's",
                                 validators=[FileExtensionValidator(['pdf'])])

    # The source with which the statement file was created (a .zip or another compression format)
    source = models.FileField(upload_to='source', blank=True, null=True)

    tests = models.FileField(upload_to='test_files', help_text="Se aceptan formatos .csv y .json",
                             validators=[FileExtensionValidator(['json', 'csv']), check_if_file_is_valid])
    clase = models.ForeignKey(Clase, blank=True, null=True, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        """
        On save, update timestamps
        """
        if not self.id:
            self.fecha_creacion = timezone.now()
        self.updated_at = timezone.now()

        return models.Model.save(self, *args, **kwargs)

    def __str__(self):
        return self.titulo

    def get_source_name(self):
        return self.source.name.split("/")[-1]

    def get_statement_name(self):
        return self.statement.name.split("/")[-1]

    def get_tests_name(self):
        return self.tests.name.split("/")[-1]


@receiver(post_save, sender=Problema)
def create_assignment(sender, instance, created, **kwargs):
    """
    Changes the file to a json on creation

    :param sender: The model class. (Assignment)
    :param instance: The actual instance being saved.
    :param created: Boolean; True if a new record was created.
    """

    if created and instance.tests:
        # Generates paths for the new json file
        test_url = instance.tests.url[1:]
        json_tests_url = change_path_extension(test_url, 'json')

        # Passes the information from the original file to the json file
        file_to_file(test_url, json_tests_url)

        # Saves the new json file as the tests file in the instance
        f = open(json_tests_url)
        instance.tests.save(get_file_name(json_tests_url), File(f))
        f.close()

        # Deletes the old file
        os.remove(test_url)
        create_test_cases(instance)


def create_test_cases(problema):
    with open(settings.BASE_DIR + problema.tests.url, 'r', encoding='utf-8-sig') as f:
        datastore = json.load(f)

    for test_dict in datastore:  # Aquí es donde se generan los test, tengo que modificar para que reciba mi nueva info.
        caso = Caso(categoría=test_dict["Categoria"], input=test_dict["Input"], output_esperado=test_dict["Output"],
                    problema=problema)
        caso.save()


class Caso(models.Model):
    categoría = models.TextField(help_text="Descripción del caso")
    input = models.CharField(max_length=255, help_text="Input del caso")
    output_esperado = models.CharField(max_length=255, help_text="Output esperado para el input")
    problema = models.ForeignKey(Problema, on_delete=models.CASCADE, help_text="Problema al que pertenece el caso")

    def __str__(self):
        return self.problema.titulo + "-" + str(self.id)

cursos/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View

from NiñasProject.decorators import docente_required
from asistencia.utils import clases_asistencias_alumna, porcentaje_asistencia

from clases.models import Clase
from cursos.models import Curso
from feedback.models import Feedback
from problemas.models import Problema
from usuarios.models import User

#Vista padre de los cursos
class CursosView(LoginRequiredMixin, View):
    login_url = 'usuarios:login'
    redirect_field_name = ''

    def get_cursos(self, username):
        """
        Método que entrega los cursos en los que username es docente
        :param username: usuario a buscar
        :return: lista de cursos
        """
        usuaria = User.objects.get(username=username)
        if usuaria.es_profesora:
            cursos = Curso.objects.filter(profesoras__in=[usuaria])
        elif usuaria.es_voluntaria:
            cursos = Curso.objects.filter(voluntarias__in=[usuaria])
        elif usuaria.es_alumna:
            cursos = Curso.objects.filter(alumnas__in=[usuaria])
        return list(cursos)


class CursoView(CursosView):

    def get(self, request, **kwargs ):
        curso_id = kwargs['curso_id']
        curso = get_object_or_404(Curso, pk=curso_id)
        if 'order' not in kwargs:
            orden = 'oldest'
        else:
            orden = kwargs['order']

        if curso in self.get_cursos(request.user.username):
            usuaria = request.user
            clases_totales = Clase.objects.filter(curso=curso)
            if orden == 'newest':
                clases_totales = clases_totales.order_by('-fecha_clase')
            clases_asistencias = clases_asistencias_alumna(usuaria=usuaria, curso=curso)
            feedbacks = self.get_feedbacks_alumna(usuaria,clases_totales)

            parameters = {
                'curso': curso,
                'usuaria': usuaria,
                'clases' : clases_totales,
                'porcentaje_asistencia': porcentaje_asistencia(usuaria=usuaria, curso=curso),
                'clases_asistencias': clases_asistencias,
                'nro_clases_totales': max(len(clases_totales), curso.cant_clases),
                'nro_clases_realizadas': len(clases_asistencias),
                'feedbacks':feedbacks,
                'order': orden
            }
            return render(request, 'cursos/inicio_curso.html', parameters)
        else:
            messages.success(request, "No tienes permiso para ver ese curso")
            return HttpResponseRedirect(reverse('usuarios:index'))

    def post(self, request,**kwargs):
        id_clase = request.POST['id_clase']
        clase_edit = Clase.objects.get(id=id_clase)
        edit_correct = True

        if request.POST.get('fecha_clase'):
            #no puede haber dos clases un mismo día.
            clase_mismo_dia = Clase.objects.filter(fecha_clase=request.POST.get('fecha_clase'),curso=clase_edit.curso)
            if len(clase_mismo_dia) == 0 or clase_mismo_dia.first()==clase_edit:
                clase_edit.fecha_clase = request.POST['fecha_clase']
            else:
                messages.error(request,f"No se actualizó la clase {clase_edit.nombre}, ya existe una clase para la fecha ingresada")
                edit_correct = False

        if edit_correct:
            if request.POST.get('publica'):
                clase_edit.publica = True
            else:
                clase_edit.publica = False

            if request.POST.get('nombre'):
                clase_edit.nombre = request.POST['nombre']
            messages.success(request, "La clase se editó correctamente")

        clase_edit.save()
        return HttpResponseRedirect(reverse('cursos:curso',kwargs=kwargs))

    def get_feedbacks_alumna(self, usuaria, clases_totales):
        result = {}
        for clase in clases_totales:
            for problema in clase.problema_set.all():
                result[problema.id] = Feedback.objects.filter(user=usuaria, problema=problema).order_by('fecha_envio').last()
        return result

@method_decorator([docente_required], name='dispatch')
class MisCursosView(CursosView):

    def get(self, request):
        if request.user.es_profesora  or request.user.es_voluntaria :
            cursos = self.get_cursos(request.user.username)
            return render(request, 'cursos/mis_cursos.html', {'cursos': cursos})
        else:
            return HttpResponseRedirect(reverse('usuarios:index'))


@method_decorator([docente_required], name='dispatch')
class EstadisticasView(LoginRequiredMixin, View):
    login_url = 'usuarios:login'
    redirect_field_name = ''

    def get(self, request, **kwargs):
        curso_id = kwargs["curso_id"]
        curso = get_object_or_404(Curso, id=curso_id, profesoras__in=[request.user])
        clases = Clase.objects.filter(curso=curso, publica=True)
        feedback_alumnas = self.get_feedbacks_curso(curso)

        clases = Clase.objects.filter(curso=curso, publica=True)
        total_problemas = 0
        for clase in clases:
            total_problemas += Problema.objects.filter(clase=clase).count()

        hay_alumnas = True
        hay_clases = True

        if len(feedback_alumnas) == 0:
            hay_alumnas = False
        if len(clases) == 0:
            hay_clases = False

        parameteres = {
            'curso': curso,
            'clases': clases,
            'feedback_alumnas': feedback_alumnas,
            'hay_alumnas': hay_alumnas,
            'hay_clases': hay_clases,
            'total_problemas': total_problemas
        }

        return render(request, 'cursos/tabla_estadisticas.html', parameteres)


    def get_feedbacks_curso(self, curso):
        clases = Clase.objects.filter(curso=curso, publica=True)
        alumnas = curso.alumnas.all()
        result = {}
        for alumna in alumnas:
            alu_resultado = {'alumna': alumna, 'feedbacks': {}}
            resueltos = 0
            intentos = 0
            enviados = 0
            for clase in clases:
                for problema in clase.problema_set.all():
                    feedback_correctos = Feedback.objects.filter(user=alumna, problema=problema, resultado=True)
                    feedback_incorrectos = Feedback.objects.filter(user=alumna, problema=problema, resultado=False)

                    # feedback corresponde a la última solución correcta o a la última (si no hay correctas)
                    if feedback_correctos:
                        feedback = feedback_correctos.order_by('fecha_envio').last()
                    else:
                        feedback = feedback_incorrectos.order_by('fecha_envio').last()

                    incorrectos = feedback_incorrectos.count()
                    correctos = feedback_correctos.count()

                    # hay que preguntar si feedback existe, puede no haber ninguna solución enviada
                    if feedback:
                        intentos += 1
                        enviados += incorrectos + correctos
                        if correctos > 0:
                            resueltos += 1
                    alu_resultado['feedbacks'][problema.id] = [feedback, incorrectos, correctos]
            result[alumna.id] = [alu_resultado, resueltos, intentos, enviados]
        return result

cursos/templates/cursos/inicio_curso.html
{% extends 'menu.html' %}
{% load static %}
{% load template_tags %}
{% block title %}{{ curso.nombre }}{% endblock %}


{% block content %}

{% if hay_curso %}
    <!-- Mensaje de creación exitosa de curso -->
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                 <div class="alert">
                  <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                  {{message}}
                </div>
            {% endfor %}
        </ul>
    {% endif %}

    <div class='title-and-button' >
        <div>
            <h1>{{ curso.nombre }}</h1>
            <p class="flex-center" style="justify-content: left"><i class="material-icons curso-icons">place</i>{{ curso.sede.nombre }}
                            <i class="material-icons curso-icons date-icon">date_range</i>{{ curso.anho }}</p>
        </div>
        {% if usuaria.es_profesora %}
            <a href="{% url 'clases:agregar_clase' curso_id=curso.id %}" class="waves-effect waves-light btn-large btn" >Agregar clase</a>
        {% endif %}
    </div>

    {% if usuaria.es_alumna %}

        <div class="modulo-asistencia">

            <div class="flex-container">

                <!-- TÍTULO ASISTENCIA -->
                <div>
                    <h4> Asistencia </h4>
                </div>

                <!-- MODAL -->
                <div>
                    <!-- Modal Trigger -->
                    <div>
                        <div class="material-icons right">
                            <a href="#modal1" class="waves-effect waves-light btn-small btn modal-trigger"> <i class="material-icons right">search</i> Ver Detalle </a>
                        </div>
                    </div>

                    <!-- Modal Structure -->
                    <div id="modal1" class="modal">

                                <div class="modal-content">

                                  <h4>Tu Asistencia</h4>

                                    <p> Se han desarrollado {{nro_clases_realizadas}} clases de un total de {{nro_clases_totales}}. </p>

                                    <center>
                                        <table class="highlight tabla-asistencia-alumna">
                                            <thead>
                                              <tr>
                                                <th> Clase </th>
                                                <th> Asistio </th>
                                              </tr>
                                            </thead>
                                            <tbody>
                                                {% for lista in clases_asistencias %}
                                                    <tr>
                                                        <td> {{lista.0.nombre}} </td>
                                                        {% if lista.1 %}
                                                            <td>  <i class="material-icons icon-green">check</i> </td>
                                                        {% else %}
                                                            <td>  <i class="material-icons icon-red">clear</i> </td>
                                                        {% endif %}
                                                    </tr>
                                                {% endfor %}
                                            </tbody>

                                        </table>
                                    </center>
                                </div>

                                <div class="modal-footer">
                                    <div class="material-icons right">
                                        <a href="" class="modal-action modal-close waves-effect waves-light btn-small btn">
                                            <i class="material-icons right">check</i>Ok</a>
                                    </div>
                                </div>

                    </div>
                </div>

            </div>



            <div class="row flex-container">
                <div class="col s10">
                    <div class="progress">
                        <div class="determinate" style=" width: {{porcentaje_asistencia}}%"></div>
                    </div>
                </div>

                <div class="col s1" style="font-size:larger;">
                    {{ porcentaje_asistencia }}%
                </div>

                <div class="col s1"></div>
            </div>


        </div>
    {% endif %}
    <div>
        <a id="sort-button" class="btn-small btn btn-sort" onclick="cambiar_orden()">
            {% if order == 'newest' %}
                Más recientes primero
            {% else %}
                Más antiguas primero
            {% endif %}
            <i class="material-icons right">cached</i></a>
    </div>
    <ul class="collection collection-principal" id="lista-clases">
        {% if clases %}
            {% for clase in clases %}
                {% if clase.publica or not usuaria.es_alumna %}
                    <li class="collection-item publica{{ clase.publica }} items-clase">
                        <div id="clase_{{ clase.id }}" class="collection-info">
                            <p><b>{{ clase.nombre }}</b> <span id="la-fecha" class="fecha-texto fecha_clase">&nbsp; {{ clase.fecha_clase }}</span></p>
                            <div style="display: flex; align-items: center">
                                {% if user.es_profesora %}
                                    {% if clase.publica %} <p>Publicada</p>
                                    {% else %} <p>No publicada</p>
                                    {% endif %}
                                    <a class="btn-floating btn-small btn" style="margin-left: 10px" onclick="editar_clase({{ clase.id }})">
                                        <i class="tiny material-icons">create</i>
                                    </a>
                                {% endif %}
                            </div>
                        </div>
                        {% if user.es_profesora %}
                            <div style = "display:none" id="clase_edit_{{ clase.id }}">
                                <form method="post" action="" style="width: 100%">

                                    {% csrf_token %}

                                    <input type="hidden" value="{{ clase.id }}" name="id_clase">
                                    <div class="title-and-button">
                                        <div class="title-and-button">
                                            <div class="input-field ">
                                                <i class="material-icons prefix">mode_edit</i>
                                                <input value="{{ clase.nombre }}"  type='text' class='validate' name="nombre">
                                                <label class='active' for='clase_edit_" + id_clase + "'>Clase {{ forloop.counter }}:</label>
                                            </div>
                                            <div>
                                                <input value="{{ clase.fecha_clase.year }}-{{ clase.fecha_clase.month }}-{{ clase.fecha_clase.day }}" type="text" id="fecha_clase" class="datepicker" name="fecha_clase">
                                                <label class="active" for="fecha_clase">Fecha clase </label>
                                            </div>
                                        </div>
                                        <div>
                                            <a class="btn-floating btn-small btn" style="margin-left: 10px;float:right" onclick="cerrar_edicion_clase({{ clase.id }})"><i class="tiny material-icons">close</i></a>
                                        </div>
                                    </div>

                                    <div class="switch" style="align-self: start">
                                        <label>
                                            {% if clase.publica %}
                                                <input type="checkbox" name="publica"  checked="checked" />
                                            {% else %}
                                                <input type="checkbox" name="publica"/>
                                            {% endif %}
                                            <span>Pública</span>
                                        </label>
                                        <div>
                                            <button type="submit"  class="waves-effect waves-light btn-small btn btn-save">Guardar</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        {% endif %}

                        <div id="problemas">
                            <hr class="problemas-line">
                            <div class="title-and-button">
                                {% if clase.problema_set.all %}
                                    <p>Problemas de la clase:</p>
                                {% else %}
                                    <p>Aún no hay problemas</p>
                                {% endif %}
                                {% if usuaria.es_profesora %}
                                    <a href="{%  url 'problemas:crear-problema' clase_id=clase.id%}" class="btn-floating waves-effect waves-light btn-small btn"><i class="material-icons">add</i></a>
                                {% endif %}
                            </div>

                            <ul class="collection collection-pequena">

                                {% for problema in clase.problema_set.all %}
                                <li class="collection-item title-and-button">
                                    <div>
                                        <a href="{% url 'problemas:enunciado-problema' curso_id=curso.id problema_id=problema.id result=1%}">
                                            {{ problema }}
                                        </a>
                                    </div>
                                    {% with feedbacks|lookup:problema.id as feedback %}
                                        {% if feedback and feedback.resultado == True %}
                                            <div class="secondary-content" style="color: green"> Completo </div>
                                        {% elif feedback and feedback.resultado == False %}
                                            <div class="secondary-content" style="color: darkorange">Incompleto </div>
                                        {% endif %}
                                    {% endwith %}
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </li>
                {% endif %}
            {% endfor %}
        {% else %}
            <li class="collection-item">
                No hay clases disponibles para este curso.
            </li>
        {% endif %}
    </ul>

    {% else %} <!-- Si no hay curso -->
        <div>
            <h2 style="text-align:center;">No tienes cursos registrados en este período!</h2>
                <div style="text-align:center;"><img src="{% static 'images/error_kitten.png' %}" alt="gatito del mensaje de error" style="width:300px;"></div>

                <p style="text-align:center;margin-top:5%;">Si estás en un curso actualmente, pide ayuda a tu tutora para que puedas ingresar.</p>
        </div>
    {% endif %}
{% endblock %}\

{% block scripts %}
    <script src={% static 'js/scripts.js' %}>

    </script>

{% endblock %}

cursos/templates/cursos/inicio_docente.html
{% extends 'base.html' %}
{% block title %}Mis Cursos{% endblock %}


{% block content %}
<h1>Mis cursos</h1>
<p><a href="{% url 'usuarios:logout' %}">logout</a></p>
{% endblock %}

cursos/templates/cursos/mis_cursos.html
{% extends 'menu.html' %}
{% load static %}
{% block title %}Mis Cursos{% endblock %}


{% block content %}
    {% if cursos %}
        <ul class=" collection with-header collapsible popout">
            <li class="collection-header" style="margin-bottom: 30px">
                    <h1>Mis cursos</h1>
            </li>

                {% for curso in cursos %}
                    {% if forloop.first %}
                        <li class="active">
                    {% else %}
                        <li>
                    {% endif %}
                    <div class="collapsible-header">
                        <div>
                            <h5><p class="title-mis-cursos">{{ curso.nombre }}</p></h5>
                            <p class="flex-center"><i class="material-icons curso-icons">place</i>{{ curso.sede.nombre }}
                            <i class="material-icons curso-icons date-icon">date_range</i>{{ curso.anho }}</p>
                        </div>
                    </div>
                    <div class="collapsible-body">

                        <a href="{% url 'cursos:curso' curso_id=curso.id %}" class="waves-effect waves-light btn btn-large"><i class="material-icons right">school</i>Clases y problemas</a>

                        <a href="{% url 'cursos:estadisticas' curso_id=curso.id %}" class="waves-effect waves-light btn btn-large"><i class="material-icons right">show_chart</i>Avance estudiantes</a>

                        <a href="{% url 'asistencia:asistencia_gral' curso_id=curso.id %}" class="waves-effect waves-light btn btn-large "><i class="material-icons right">format_list_bulleted</i>Asistencia</a>
                    </div>
                </li>
                {% endfor %}

        </ul>
    {% else %}
        <ul class="collection with-header">
        <li class="collection-header"><h1>Mis cursos</h1></li>
        <li class="collection-item">No hay cursos disponibles</li>

      </ul>

    {% endif %}

{% endblock %}
{% block scripts %}
    <script src={% static 'js/scripts.js' %}></script>

{% endblock %}

cursos/templates/cursos/pagina_error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error</title>
</head>
<body>
 {% if error_message %}<small class="red-text"><strong>{{ error_message }}</strong></small>{% endif %}
</body>
</html>