NiñasProject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

import usuarios

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("usuarios.urls")),
    path('', include("cursos.urls")),
    path('coordinadora/', include("coordinacion.urls", namespace='coordinacion')),
    path('', include("asistencia.urls")),
    path('',include("problemas.urls")),
    path('',include("clases.urls")),
    path('',include("feedback.urls")),
] +static(settings.MEDIA_URL, document_ROOT=settings.MEDIA_ROOT)

clases/urls.py
from django.urls import path, include

from clases import views

app_name = 'clases'
urlpatterns = [
    path('<int:curso_id>/agregar-clase/', views.CrearClaseView.as_view(), name='agregar_clase'),
]

coordinacion/urls.py
from django.urls import path, include

from coordinacion import views

app_name = 'coordinadora'
urlpatterns = [
    path('inicio/', views.CoordinadoraInicioView.as_view(), name='inicio_coordinadora'),
    path('cursos', views.CoordinadoraCursosView.as_view(), name='cursos'),
    path('cursos/crear', views.CoordinadoraCrearCursosView.as_view(), name='crear_curso'),
    path('cursos/editar/<int:curso_id>', views.CoordinadoraEditarCursosView.as_view(), name='editar_curso'),
    path('cursos/eliminar/<int:curso_id>', views.eliminar_curso , name='eliminar_curso'),
    path('curso/eliminar_cursos', views.eliminar_cursos, name='eliminar_cursos'),
    path('users', views.CoordinadoraUsersView.as_view(), name = 'users'),
    path('users/crear', views.CoordinadoraCrearUserView.as_view(), name = 'crear_user'),
    path('users/editar/<int:user_id>', views.CoordinadoraEditarUsersView.as_view(), name = 'editar_users'),
    path('users/eliminar/<int:user_id>', views.eliminar_user, name = 'eliminar_user'),
    path('users/eliminar_users', views.eliminar_users, name = 'eliminar_users')
]

cursos/urls.py
from django.urls import path, include

from cursos import views

app_name = 'cursos'
urlpatterns = [
    path('<int:curso_id>/curso/', views.CursoView.as_view(), name='curso'),
    path('<int:curso_id>/curso/<str:order>/', views.CursoView.as_view(), name='curso'),
    path('mis_cursos/', views.MisCursosView.as_view(), name='mis_cursos'),
    path('<int:curso_id>/estadisticas/', views.EstadisticasView.as_view(), name='estadisticas'),

]

coordinacion/models.py
from django.db import models

# Create your models here.
from usuarios.models import User


class Sede(models.Model):
    nombre = models.CharField(max_length=100, default="Sede", primary_key=True)
    profesoras = models.ManyToManyField(User, related_name="sedes_profesoras", blank=True)
    voluntarias = models.ManyToManyField(User, related_name="sedes_voluntarias", blank=True)
    alumnas = models.ManyToManyField(User, related_name="sedes_alumnas", blank=True)
    coordinadora = models.ForeignKey(User, related_name="sedes_coordinadora", null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.nombre

cursos/models.py
from django.db import models
import datetime

# Create your models here.
from usuarios.models import User
from coordinacion.models import Sede

class Tema(models.Model):
    nombre = models.CharField(max_length=50)


class Curso(models.Model):
    class Meta:
        unique_together = (('nombre', 'anho', 'sede'),)

    nombre = models.CharField(max_length=100, default="curso_default")
    profesoras = models.ManyToManyField(User, related_name="profesoras", blank=True)
    voluntarias = models.ManyToManyField(User, related_name="voluntarias", blank=True)
    alumnas = models.ManyToManyField(User, related_name="alumnas", blank=True)
    tema = models.ManyToManyField(Tema, related_name="tags", blank=True)
    cant_clases = models.IntegerField(default=1)
    anho = models.IntegerField(default=datetime.datetime.now().year)
    sede = models.ForeignKey(Sede, on_delete=models.CASCADE, to_field="nombre", blank=True, null=True)

    def __str__(self):
        return self.nombre

coordinacion/forms.py
from django.forms import ModelForm

from django.forms.widgets import CheckboxInput
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator

from cursos.models import Curso
from usuarios.models import User

from django import forms


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'es_profesora','es_alumna','es_voluntaria']

class CursoForm(ModelForm):
    lista_alumnas = forms.FileField(required=False, help_text="Solo se acepta formato csv",validators=[FileExtensionValidator(['json', 'csv'])])
    class Meta:
        model = Curso
        fields = ['nombre', 'profesoras', 'voluntarias', 'alumnas']

coordinacion/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.utils.decorators import method_decorator
from NiñasProject.decorators import coordinadora_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.edit import UpdateView, CreateView, FormView
from django.contrib import messages
from coordinacion.forms import UserForm, CursoForm
from django.core.exceptions import ValidationError
from usuarios.management.commands.crear_users import Command
from my_lib.files_wrapper import create_temp_file
from django.core.files import File

import os
import csv
import datetime

from coordinacion.models import Sede
from cursos.models import Curso
from usuarios.models import User
# Create your views here.
from django.views import View

@method_decorator([coordinadora_required], name='dispatch')
class CoordinadoraInicioView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'coordinacion/inicio_coordinadora.html')

# CURSOS VIEWS
@method_decorator([coordinadora_required], name='dispatch')
class CoordinadoraCursosView(LoginRequiredMixin, View):
    def get(self, request):
        cursos = Curso.objects.all()
        return render(request, 'coordinacion/cursos/cursos.html', {'cursos':cursos})

@method_decorator([coordinadora_required], name='dispatch')
class CoordinadoraEditarCursosView(LoginRequiredMixin, UpdateView):
    model = Curso
    fields = ('nombre', 'profesoras', 'voluntarias', 'alumnas')
    template_name = 'coordinacion/cursos/editar_curso.html'
    pk_url_kwarg = 'curso_id'
    context_object_name = 'curso'
    
    def get_form(self):
        form = super().get_form()
        sede = Sede.objects.get(coordinadora=self.request.user)
        form.fields['profesoras'].queryset = sede.profesoras.filter(es_profesora=True, is_active=True)
        form.fields['alumnas'].queryset = sede.alumnas.filter(es_alumna=True, is_active=True)
        form.fields['voluntarias'].queryset = sede.voluntarias.filter(es_voluntaria=True, is_active=True)
        return form

    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'Curso modificado')
        return HttpResponseRedirect(reverse('coordinacion:cursos'))

@method_decorator([coordinadora_required], name='dispatch')
class CoordinadoraCrearCursosView(LoginRequiredMixin, CreateView):
    # model = Curso
    # fields = ('nombre', 'sede', 'profesoras', 'voluntarias', 'alumnas')
    template_name = 'coordinacion/cursos/crear_curso.html'
    context_object_name = 'curso'

    def get_form(self):
        form = CursoForm()
        sede = Sede.objects.get(coordinadora=self.request.user)
        form.fields['nombre'].initial = ""
        form.fields['profesoras'].queryset = sede.profesoras.filter(es_profesora=True, is_active=True)
        form.fields['alumnas'].queryset = sede.alumnas.filter(es_alumna=True, is_active=True)
        form.fields['voluntarias'].queryset = sede.voluntarias.filter(es_voluntaria=True, is_active=True)
        return form

    def post(self, request, *args, **kwargs):
        try:
            filename = self.validate(request)
        except Exception as e:
            messages.success(request, e)
            return HttpResponseRedirect(reverse('coordinacion:crear_curso'))
        self.form_valid(request, filename)
        messages.success(self.request, 'Curso creado')
        return HttpResponseRedirect(reverse('coordinacion:cursos'))


    def validate(self, request):
        user = request.user
        form = request.POST
        sede = Sede.objects.get(coordinadora=user)
        if len(Curso.objects.filter(nombre=form['nombre'], anho = datetime.datetime.now().year, sede=sede.nombre))>0:
            raise ValidationError("Ya existe un curso con este nombre este año en esta sede")
        lista = request.FILES.get('lista_alumnas')
        if lista!=None:
            filename = create_temp_file(File(lista), 'csv')
            with open(filename, 'r') as lista:
                try:
                    Command().csvValidator(lista)
                except Exception as e:
                    if os.path.exists(filename):
                        os.remove(filename)
                    raise e
            return filename
        else:
            return None

    def form_valid(self, request, filename):
        form = request.POST
        user = request.user
        sede = Sede.objects.get(coordinadora=user)
        curso = Curso.objects.create(nombre=form.get('nombre'), sede=sede)
        for profesora in form.getlist('profesoras'):
            curso.profesoras.add(profesora)
        if filename!=None:
            with open(filename, 'r', encoding='utf-8-sig') as csvFile:
                Command().create('alumnas', sede, curso, csvFile)
            if os.path.exists(filename):
                os.remove(filename)
        for alumna in form.getlist('alumnas'):
            if not curso.alumnas.filter(id=alumna).exists():
                curso.alumnas.add(alumna)
        for voluntaria in form.getlist('voluntarias'):
            curso.voluntarias.add(voluntaria)
        curso.save()


@coordinadora_required
def eliminar_curso(request, curso_id):
    Curso.objects.get(id=curso_id).delete()
    return HttpResponseRedirect(reverse('coordinacion:cursos'))

@coordinadora_required
def eliminar_cursos(request):
    cursos_id = request.POST.getlist('cursos_delete')
    for curso_id in cursos_id:
        Curso.objects.get(id=curso_id).delete()
    messages.success(request, 'Cursos eliminados')
    return HttpResponseRedirect(reverse('coordinacion:cursos'))

#USERS VIEWS

@method_decorator([coordinadora_required], name='dispatch')
class CoordinadoraUsersView(LoginRequiredMixin, View):
    def get(self, request):
        sede = Sede.objects.get(coordinadora=self.request.user)
        profesoras = sede.profesoras.filter(es_profesora=True, is_active=True)
        alumnas = sede.alumnas.filter(es_alumna=True, is_active=True)
        voluntarias = sede.voluntarias.filter(es_voluntaria=True, is_active=True)
        return render(request, 'coordinacion/users/users_index.html', {'profesoras':profesoras, 'alumnas':alumnas, 'voluntarias':voluntarias})

@method_decorator([coordinadora_required], name='dispatch')
class CoordinadoraEditarUsersView(LoginRequiredMixin, UpdateView):
    model = User
    fields = ('first_name', 'last_name', 'es_alumna', 'es_voluntaria', 'es_profesora')
    template_name = 'coordinacion/users/editar_user.html'
    pk_url_kwarg = 'user_id'
    context_object_name = 'user'

    def form_valid(self, form):
        user = form.save()
        sede = Sede.objects.get(coordinadora=self.request.user)
        sede.profesoras.remove(user)
        sede.voluntarias.remove(user)
        sede.alumnas.remove(user)
        if user.es_voluntaria:
            sede.voluntarias.add(user)
        if user.es_profesora:
            sede.profesoras.add(user)
        if user.es_alumna:
            sede.alumnas.add(user)

        messages.success(self.request, 'Usuaria modificada')
        return HttpResponseRedirect(reverse('coordinacion:users'))

@method_decorator([coordinadora_required], name='dispatch')
class CoordinadoraCrearUserView(LoginRequiredMixin, FormView):
    form_class = UserForm
    template_name = 'coordinacion/users/crear_user.html'

    def form_valid(self, form):
        data = form.cleaned_data
        user = User.objects.create_user(first_name=data['first_name'], last_name=data['last_name'], username=data['username'],
               password='tempPass21', es_profesora=data['es_profesora'], es_alumna=data['es_alumna'], es_voluntaria=data['es_voluntaria'])
        user.save()
        sede = Sede.objects.get(coordinadora=self.request.user)
        if data['es_profesora']:
            sede.profesoras.add(user)
        if data['es_voluntaria']:
            sede.voluntarias.add(user)
        if data['es_alumna']:
            sede.alumnas.add(user)
        messages.success(self.request, 'Usuaria Creada')
        return HttpResponseRedirect(reverse('coordinacion:users'))

@coordinadora_required
def eliminar_user(request, user_id):
    user = User.objects.get(id=user_id)
    user.is_active = False
    user.save()
    return HttpResponseRedirect(reverse('coordinacion:users'))

@coordinadora_required
def eliminar_users(request):
    users_id = request.POST.getlist('user_delete')
    for user_id in users_id:
        user = User.objects.get(id=user_id)
        user.is_active = False
        user.save()
    messages.success(request, 'Usuarias eliminadas')
    return HttpResponseRedirect(reverse('coordinacion:users'))

coordinacion/templates/coordinacion/cursos/crear_curso.html
{% extends 'menu.html' %}
{% load static %}
{% block title %}Crear Curso{% endblock %}


{% block content %}
<h2 style="text-align: center;">Crear Curso</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    
    <div>
        <a href="{% url 'coordinacion:inicio_coordinadora' %}" class="waves-effect waves-light btn-small btn red accent-2" >
            <i class="material-icons left">arrow_back</i>Volver</a>

            <button type="submit" class="waves-effect waves-light btn-small btn red accent-2">
                <i class="material-icons right">playlist_add_check</i>Guardar</button>

    </div>
</form>
{% endblock %}

coordinacion/templates/coordinacion/cursos/cursos.html
{% extends 'menu.html' %}
{% load static %}
{% block title %}Mis Cursos{% endblock %}


{% block content %}

{% if cursos %}
<h1>Coordinación cursos</h1>
<div class="left">
  <a href="{% url 'coordinacion:crear_curso' %}" class="waves-effect waves-light btn-small btn red accent-2">
    <i class="material-icons right">add</i>Crear</a>
</div>
<form method="post" action="{% url 'coordinacion:eliminar_cursos'%}" onsubmit="return eliminar_alerta('¿Esta segura que desea eliminar estos cursos?')" >
  {%csrf_token%}
  <div class="right" style="margin-bottom: 10px;">
    <button id="btn-1" type="submit" class="waves-effect waves-light btn-small btn red accent-2 btn-right" disabled>
      <i class="material-icons right">playlist_add_check</i>Eliminar Cursos</button>
    </div>
  <br>
  <br>
  <div class="container-tabla-users">
    <table id="cursos_table" class="display tabla-asist-gral">
      <thead>
        <tr>
          <th></th>
          <th>Curso</th>
          <th>Año</th>
        </tr>
      </thead>
      <tbody>
        {% for curso in cursos %}
        <tr>
          <td>
            <label>
              <input type="checkbox" id="{{curso.nombre}}" value={{curso.id}} name=cursos_delete onclick="clicked(this.checked, this.id)" />
              <span></span>
            </label>
          </td>
          <td><a href="{% url 'coordinacion:editar_curso' curso.id %}">{{curso.nombre}}</a></td>
          <td>{{curso.anho}}</td>
        </tr>
        {%endfor%}
      </tbody>
    </table>
    </div>
 
<div class="left">
  <a href="{%url 'coordinacion:inicio_coordinadora'%}" class="waves-effect waves-light btn-small btn red accent-2" >
    <i class="material-icons left">arrow_back</i>Volver</a>
</div>
<div class="right">
  <button id="btn-2" type="submit" class="waves-effect waves-light btn-small btn red accent-2" style="margin-bottom: 10px;" disabled>
      <i class="material-icons right">playlist_add_check</i>Eliminar Cursos</button>
</div>
</form>
{%else%}
<h2 style="text-align: center;">No hay cursos en esta sede</h2>
<div class="center">
  <a href="{%url 'coordinacion:inicio_coordinadora'%}" class="waves-effect waves-light btn-small btn red accent-2" >
    <i class="material-icons left">arrow_back</i>Volver</a>
  <a href="{% url 'coordinacion:crear_curso' %}" class="waves-effect waves-light btn-small btn red accent-2">
    <i class="material-icons right">add</i>Crear</a>
</div>
{%endif%}
{% endblock %}

{% block scripts %}
    <script src={% static 'js/scripts.js' %}></script>
{% endblock %}

coordinacion/templates/coordinacion/cursos/editar_curso.html
{% extends 'menu.html' %}
{% load static %}
{% block title %}Editar Curso{% endblock %}


{% block content %}
<h2 style="text-align: center;">Editar Curso</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    
    <div>
        <a href="{% url 'coordinacion:cursos' %}" class="waves-effect waves-light btn-small btn red accent-2" >
            <i class="material-icons left">arrow_back</i>Volver</a>

            <button type="submit" class="waves-effect waves-light btn-small btn red accent-2">
                <i class="material-icons right">playlist_add_check</i>Guardar</button>

    </div>
</form>
{% endblock %}